//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Commander : Role
	{
		Player player;

		public Commander ( Player player )
		{
			this.player = player;
		}

		public override ViewStyle viewStyle ()
		{
			return ViewStyle.TOP_DOWN;
		}

		public override Commander becomeCommander ()
		{
			return this;
		}

		public override Soldier becomeSoldier ()
		{
			Soldier newRole = null;
			lock (this) {
				if (CommandBase.Instance.leave ( player )) {
					// Successfully Left the Commmand Base
					newRole = new Soldier ( player );
				}
			}
			return newRole;
		}

		public bool promptLeaveCommander()
		{
			bool success = false;
			lock (this) {
				// POP UP PROMPT
				// Assume (for now) that they always leave when prompted
				success = player.becomeSoldier();
			}
			return success;
		}
	}
}

