//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public enum ViewStyle
	{
		INVALID,
		TOP_DOWN,
		FIRST_PERSON
	}

	public enum Role
	{
		INVALID,
		SOLDIER,
		COMMANDER
	}
}

