//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Soldier : Role
	{
		Player player;

		public Soldier ( Player player )
		{
			this.player = player;
		}

		public override Commander becomeCommander ()
		{
			Commander newRole = null;
			lock ( this ) {
				if ( CommandBase.Instance.enter(player) ) {
					// Successfully Entered the Command Base
					newRole = new Commander ( player );
				}
			}
			return newRole;
		}

		public override Soldier becomeSoldier ()
		{
			return this;
		}

		public override ViewStyle viewStyle ()
		{
			return ViewStyle.FIRST_PERSON;
		}


	}
}

