//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Soldier : Role
	{
		bool becomeSoldier()
		{
			Console.WriteLine("Already a Soldier!");
			return false;
		}
		
		bool becomeCommander()
		{
			Console.WriteLine ("Attempting to become a Commander");
			if (CommandBase.Instance.enter (this)) {
				Console.WriteLine ( "You are now commander!");

			}
			return false;
		}

		public Soldier ()
		{

		}
	}
}

