//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Weapon
	{
		private string name;

		public Weapon ()
		{
			name = "Default Weapon Name";
		}

		public Weapon ( string name )
		{
			this.name = name;
		}

		public override string ToString ()
		{
			return name;
		}

	}
}

